# Generated by Django 5.0 on 2025-12-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('duration_seconds', models.IntegerField()),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('electronic', 'Electronic'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('hip-hop', 'Hip-Hop'), ('indie', 'Indie'), ('alternative', 'Alternative')], max_length=50)),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['artist', 'title'],
                'indexes': [models.Index(fields=['genre'], name='tracks_trac_genre_a6344e_idx'), models.Index(fields=['artist'], name='tracks_trac_artist_08f410_idx')],
            },
        ),
    ]
