# Generated by Django 5.0 on 2025-12-04 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(db_index=True, default=1.0)),
                ('votes', models.IntegerField(default=0)),
                ('added_by', models.CharField(default='Anonymous', max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_playing', models.BooleanField(db_index=True, default=False)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='tracks.track')),
            ],
            options={
                'ordering': ['position'],
                'indexes': [models.Index(fields=['position'], name='playlist_pl_positio_8e5e4e_idx'), models.Index(fields=['is_playing'], name='playlist_pl_is_play_6d3b42_idx'), models.Index(fields=['-votes'], name='playlist_pl_votes_051786_idx')],
            },
        ),
    ]
